# Copyright (c) 2020 Intel Corporation.
# SPDX-License-Identifier: Apache-2.0

name: Twister TestSuite

on:
  push:
    branches:
    - main
    - v*-branch
    - collab-*
    paths:
    - 'scripts/pylib/**'
    - 'scripts/twister'
    - 'scripts/tests/twister/**'
    - '.github/workflows/twister_tests.yml'
    - 'scripts/schemas/twister/'
  pull_request:
    branches:
    - main
    - v*-branch
    paths:
    - 'scripts/pylib/**'
    - 'scripts/twister'
    - 'scripts/tests/twister/**'
    - '.github/workflows/twister_tests.yml'
    - 'scripts/schemas/twister/'

permissions:
  contents: read

jobs:
  twister-tests:
    name: Twister Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-24.04]
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/checkout@v5
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --locked --all-extras --all-packages
      - name: Run tests for twisterlib
        env:
         ZEPHYR_BASE: ./
         ZEPHYR_TOOLCHAIN_VARIANT: zephyr
        run: uv run pytest scripts/tests/twister
      - name: Run pytest for pytest-twister-harness
        env:
         ZEPHYR_BASE: ./
         ZEPHYR_TOOLCHAIN_VARIANT: zephyr
        run: uv run pytest scripts/pylib/pytest-twister-harness/tests
